export {
  openai,
  detectAudioFormat,
  convertToWav,
  ensureCompatibleFormat,
  UnsupportedAudioFormatError,
  type OpenAIAudioInputFormat,
  type AudioFormat,
  voiceChat,
  voiceChatStream,
  voiceChatStreamWithTools,
  textToSpeech,
  textToSpeechStream,
  speechToText,
  speechToTextStream,
} from "./client";
