export default {
  "title": "Book your stay – DEVOCEAN Lodge",
  "desc": "Direct booking page for DEVOCEAN Lodge, Ponta do Ouro, Mozambique. Best rates, instant confirmation.",
  "home": "Home",
  "back": "Back",
  "h1": "Book here for Best Value",
  "currencyNote": "Need to convert US$ into your currency use the ",
  "currencyConverter": "currency converter",
  "howtoHeading": "How to Book",
  "howtoStep1Title": "Choose your unit",
  "howtoStep1": "Safari Tent • Comfort Tent • Garden Cottage • Thatched Chalet",
  "howtoStep2Title": "Decide on the Dates",
  "howtoStep2": "The longer you stay, the better the rate",
  "howtoStep3Title": "Fill in the number of adults/children",
  "howtoStep3": "Max. 2 adults + 1 child or 1 adult and 2 children per unit. Except for the Garden Cottage; max. 2 adults or 1 adult + 1 child",
  "howtoStep4Title": "Click the Book button",
  "howtoStep4": "And fill in the form",
  "childHeading": "Travelling with children",
  "childBabyTitle": "Babies/Infants 0-3 years",
  "childBabyPrice": "Free",
  "childBabyBooking": "Don't add during booking",
  "childBabyNote": "Add babycot on the booking form if needed or mention in the space for a note",
  "childChildrenTitle": "Children 4-11 years",
  "childChildrenPrice": "Half Price",
  "childChildrenBooking": "Add when choosing number of occupants",
  "childChildrenBed": "Extra Safari bed will be provided when total is 3",
  "childYoungsterTitle": "Youngsters 12 and up",
  "childYoungsterPrice": "Count as Adults",
  "modalTitle": "Why Book Direct?",
  "modalRate": "Best Rate Guaranteed",
  "modalRateDesc": "Lowest prices when you book directly with us",
  "modalSecure": "Secure payment",
  "modalSecureDesc": "Your data is protected with industry-standard encryption",
  "modalNofees": "No hidden fees",
  "modalNofeesDesc": "What you see is what you pay - transparent pricing",
  "modalInstant": "Instant confirmation",
  "modalInstantDesc": "Receive your booking confirmation immediately",
  "modalSupport": "DEVOCEAN Team support",
  "modalSupportDesc": "Personal assistance from our dedicated team",
  "supportTitle": "Welcome to DEVOCEAN Booking Support",
  "supportIntro": "Our team is ready to help you with:",
  "supportHelp1": "Choosing the right accommodation",
  "supportHelp2": "Understanding availability & rates",
  "supportHelp3": "Special requests",
  "supportHours": "Office Hours:",
  "supportHoursTime": "Monday-Sunday, 8:00-17:00 CAT",
  "supportButton": "Chat on WhatsApp",
  "units": {
    "safari": "Safari Tent",
    "comfort": "Comfort Tent",
    "cottage": "Garden Cottage",
    "chalet": "Thatched Chalet"
  }
};
