export default {
  "title": "Reserve su estancia – DEVOCEAN Lodge",
  "desc": "Página de reserva directa de DEVOCEAN Lodge, Ponta do Ouro, Mozambique. Mejores precios, confirmación inmediata.",
  "home": "Inicio",
  "back": "Atrás",
  "h1": "Reserve aquí al Mejor Precio",
  "currencyNote": "¿Necesitas convertir US$ a tu moneda? Usa el ",
  "currencyConverter": "convertidor de divisas",
  "howtoHeading": "Cómo reservar",
  "howtoStep1Title": "Choose your unit",
  "howtoStep4": "Safari Tent • Comfort Tent • Garden Cottage • Thatched Chalet",
  "howtoStep2Title": "Decide on the Dates",
  "howtoStep2": "The longer you stay, the better the rate",
  "howtoStep3Title": "Fill in the number of adults/children",
  "howtoStep3": "Max. 2 adults + 1 child or 1 adult and 2 children per unit. Except for the Garden Cottage; max. 2 adults or 1 adult + 1 child",
  "howtoStep4Title": "Click the Book button",
  "childHeading": "Viaja con niños",
  "childBabyTitle": "Bebés/Infantes 0-3 años",
  "childBabyPrice": "Gratis",
  "childBabyBooking": "No agregue durante la reserva",
  "childBabyNote": "Agregue cuna en el formulario de reserva si es necesario o menciónelo en el espacio para notas",
  "childChildrenTitle": "Niños 4-11 años",
  "childChildrenPrice": "Mitad de precio",
  "childChildrenBooking": "Agregue al elegir el número de ocupantes",
  "childChildrenBed": "Se proporcionará cama Safari extra cuando el total sea 3",
  "childYoungsterTitle": "Jóvenes de 12 años en adelante",
  "childYoungsterPrice": "Cuentan como adultos",
  "modalTitle": "¿Por qué reservar directo?",
  "modalRate": "Mejor Tarifa Garantizada",
  "modalRateDesc": "Precios más bajos al reservar directamente",
  "modalSecure": "Pago seguro",
  "modalSecureDesc": "Sus datos están protegidos con cifrado estándar",
  "modalNofees": "Sin cargos ocultos",
  "modalNofeesDesc": "Lo que ve es lo que paga - precios transparentes",
  "modalInstant": "Confirmación inmediata",
  "modalInstantDesc": "Reciba su confirmación de reserva de inmediato",
  "modalSupport": "Soporte del equipo DEVOCEAN",
  "modalSupportDesc": "Asistencia personal de nuestro equipo dedicado",
  "units": {
    "safari": "Tienda Safari",
    "comfort": "Tienda Comfort",
    "cottage": "Cottage de Jardín",
    "chalet": "Chalet de Paja"
  }
};