export default {
  "title": "Reserve su estancia – DEVOCEAN Lodge",
  "desc": "Página de reserva directa de DEVOCEAN Lodge, Ponta do Ouro, Mozambique. Mejores precios, confirmación inmediata.",
  "home": "Inicio",
  "back": "Atrás",
  "h1": "Reserve aquí al Mejor Precio",
  "currencyNote": "¿Necesitas convertir US$ a tu moneda? Usa el ",
  "currencyConverter": "convertidor de divisas",
  "howtoHeading": "Cómo reservar",
  "howtoStep1Title": "Elija su unidad",
  "howtoStep1": "Tienda Safari • Tienda Comfort • Garden Cottage • Chalet de Paja",
  "howtoStep2Title": "Decida las fechas",
  "howtoStep2": "Cuanto más tiempo se quede, mejor será la tarifa",
  "howtoStep3Title": "Ingrese el número de adultos/niños",
  "howtoStep3": "Máx. 2 adultos + 1 niño o 1 adulto y 2 niños por unidad. Excepto para el Garden Cottage; máx. 2 adultos o 1 adulto + 1 niño",
  "howtoStep4Title": "Haga clic en el botón Reservar",
  "howtoStep4": "Y complete el formulario",
  "childHeading": "Viaja con niños",
  "childBabyTitle": "Bebés/Infantes 0-3 años",
  "childBabyPrice": "Gratis",
  "childBabyBooking": "No agregue durante la reserva",
  "childBabyNote": "Agregue cuna en el formulario de reserva si es necesario o menciónelo en el espacio para notas",
  "childChildrenTitle": "Niños 4-11 años",
  "childChildrenPrice": "Mitad de precio",
  "childChildrenBooking": "Agregue al elegir el número de ocupantes",
  "childChildrenBed": "Se proporcionará cama Safari extra cuando el total sea 3",
  "childYoungsterTitle": "Jóvenes de 12 años en adelante",
  "childYoungsterPrice": "Cuentan como adultos",
  "modalTitle": "¿Por qué reservar directo?",
  "modalRate": "Mejor Tarifa Garantizada",
  "modalRateDesc": "Precios más bajos al reservar directamente",
  "modalSecure": "Pago seguro",
  "modalSecureDesc": "Sus datos están protegidos con cifrado estándar",
  "modalNofees": "Sin cargos ocultos",
  "modalNofeesDesc": "Lo que ve es lo que paga - precios transparentes",
  "modalInstant": "Confirmación inmediata",
  "modalInstantDesc": "Reciba su confirmación de reserva de inmediato",
  "modalSupport": "Soporte del equipo DEVOCEAN",
  "modalSupportDesc": "Asistencia personal de nuestro equipo dedicado",
  "supportTitle": "Bienvenido al Soporte de Reservas DEVOCEAN",
  "supportIntro": "Nuestro equipo está listo para ayudarte con:",
  "supportHelp1": "Elegir el alojamiento adecuado",
  "supportHelp2": "Entender disponibilidad y tarifas",
  "supportHelp3": "Solicitudes especiales",
  "supportHours": "Horario de Atención:",
  "supportHoursTime": "Lunes-Domingo, 8:00-17:00 CAT",
  "supportButton": "Chatear en WhatsApp",
  "units": {
    "safari": "Tienda Safari",
    "comfort": "Tienda Comfort",
    "cottage": "Cottage de Jardín",
    "chalet": "Chalet de Paja"
  }
};