export default {
  "title": "Réservez votre séjour – DEVOCEAN Lodge",
  "desc": "Page de réservation directe de la DEVOCEAN Lodge, Ponta do Ouro, Mozambique. Meilleurs tarifs, confirmation immédiate.",
  "home": "Accueil",
  "back": "Retour",
  "h1": "Réservez ici au Meilleur Prix",
  "currencyNote": "Besoin de convertir US$ dans votre devise? Utilisez le ",
  "currencyConverter": "convertisseur de devises",
  "howtoHeading": "Comment réserver",
  "howtoStep1Title": "Choisissez votre hébergement",
  "howtoStep1": "Tente Safari • Tente Comfort • Garden Cottage • Chalet de Chaume",
  "howtoStep2Title": "Choisissez les dates",
  "howtoStep2": "Plus vous restez longtemps, meilleur est le tarif",
  "howtoStep3Title": "Indiquez le nombre d'adultes/enfants",
  "howtoStep3": "Max. 2 adultes + 1 enfant ou 1 adulte et 2 enfants par unité. Sauf pour le Garden Cottage; max. 2 adultes ou 1 adulte + 1 enfant",
  "howtoStep4Title": "Cliquez sur Réserver",
  "howtoStep4": "Et remplissez le formulaire",
  "childHeading": "Vous voyagez avec des enfants",
  "childBabyTitle": "Bébés/Nourrissons 0-3 ans",
  "childBabyPrice": "Gratuit",
  "childBabyBooking": "Ne pas ajouter lors de la réservation",
  "childBabyNote": "Ajoutez un lit bébé sur le formulaire de réservation si nécessaire ou mentionnez-le dans l'espace pour notes",
  "childChildrenTitle": "Enfants 4-11 ans",
  "childChildrenPrice": "Demi-tarif",
  "childChildrenBooking": "Ajoutez lors du choix du nombre d'occupants",
  "childChildrenBed": "Un lit Safari supplémentaire sera fourni lorsque le total est de 3",
  "childYoungsterTitle": "Jeunes de 12 ans et plus",
  "childYoungsterPrice": "Comptent comme adultes",
  "modalTitle": "Pourquoi réserver en direct?",
  "modalRate": "Meilleur Tarif Garanti",
  "modalRateDesc": "Prix les plus bas en réservant directement",
  "modalSecure": "Paiement sécurisé",
  "modalSecureDesc": "Vos données sont protégées par un cryptage standard",
  "modalNofees": "Aucun frais caché",
  "modalNofeesDesc": "Ce que vous voyez est ce que vous payez - tarifs transparents",
  "modalInstant": "Confirmation immédiate",
  "modalInstantDesc": "Recevez votre confirmation de réservation immédiatement",
  "modalSupport": "Support de l'équipe DEVOCEAN",
  "modalSupportDesc": "Assistance personnelle de notre équipe dédiée",
  "supportTitle": "Bienvenue au Support de Réservation DEVOCEAN",
  "supportIntro": "Notre équipe est prête à vous aider avec:",
  "supportHelp1": "Choisir le bon hébergement",
  "supportHelp2": "Comprendre la disponibilité et les tarifs",
  "supportHelp3": "Demandes spéciales",
  "supportHours": "Heures d'ouverture:",
  "supportHoursTime": "Lundi-Dimanche, 8:00-17:00 CAT",
  "supportButton": "Discuter sur WhatsApp",
  "units": {
    "safari": "Tente Safari",
    "comfort": "Tente Comfort",
    "cottage": "Cottage de Jardin",
    "chalet": "Chalet de Chaume"
  }
};