export default {
  "title": "Réservez votre séjour – DEVOCEAN Lodge",
  "desc": "Page de réservation directe de la DEVOCEAN Lodge, Ponta do Ouro, Mozambique. Meilleurs tarifs, confirmation immédiate.",
  "home": "Accueil",
  "back": "Retour",
  "h1": "Réservez ici au Meilleur Prix",
  "currencyNote": "Besoin de convertir US$ dans votre devise? Utilisez le ",
  "currencyConverter": "convertisseur de devises",
  "howtoHeading": "Comment réserver",
  "howtoStep1Title": "Choose your unit",
  "howtoStep4": "Safari Tent • Comfort Tent • Garden Cottage • Thatched Chalet",
  "howtoStep2Title": "Decide on the Dates",
  "howtoStep2": "The longer you stay, the better the rate",
  "howtoStep3Title": "Fill in the number of adults/children",
  "howtoStep3": "Max. 2 adults + 1 child or 1 adult and 2 children per unit. Except for the Garden Cottage; max. 2 adults or 1 adult + 1 child",
  "howtoStep4Title": "Click the Book button",
  "childHeading": "Vous voyagez avec des enfants",
  "childBabyTitle": "Bébés/Nourrissons 0-3 ans",
  "childBabyPrice": "Gratuit",
  "childBabyBooking": "Ne pas ajouter lors de la réservation",
  "childBabyNote": "Ajoutez un lit bébé sur le formulaire de réservation si nécessaire ou mentionnez-le dans l'espace pour notes",
  "childChildrenTitle": "Enfants 4-11 ans",
  "childChildrenPrice": "Demi-tarif",
  "childChildrenBooking": "Ajoutez lors du choix du nombre d'occupants",
  "childChildrenBed": "Un lit Safari supplémentaire sera fourni lorsque le total est de 3",
  "childYoungsterTitle": "Jeunes de 12 ans et plus",
  "childYoungsterPrice": "Comptent comme adultes",
  "modalTitle": "Pourquoi réserver en direct?",
  "modalRate": "Meilleur Tarif Garanti",
  "modalRateDesc": "Prix les plus bas en réservant directement",
  "modalSecure": "Paiement sécurisé",
  "modalSecureDesc": "Vos données sont protégées par un cryptage standard",
  "modalNofees": "Aucun frais caché",
  "modalNofeesDesc": "Ce que vous voyez est ce que vous payez - tarifs transparents",
  "modalInstant": "Confirmation immédiate",
  "modalInstantDesc": "Recevez votre confirmation de réservation immédiatement",
  "modalSupport": "Support de l'équipe DEVOCEAN",
  "modalSupportDesc": "Assistance personnelle de notre équipe dédiée",
  "units": {
    "safari": "Tente Safari",
    "comfort": "Tente Comfort",
    "cottage": "Cottage de Jardin",
    "chalet": "Chalet de Chaume"
  }
};