export default {
  "title": "Prenota il tuo soggiorno – DEVOCEAN Lodge",
  "desc": "Pagina di prenotazione diretta della DEVOCEAN Lodge, Ponta do Ouro, Mozambico. Migliori tariffe, conferma immediata.",
  "home": "Home",
  "back": "Indietro",
  "h1": "Prenota qui al Miglior Prezzo",
  "currencyNote": "Hai bisogno di convertire US$ nella tua valuta? Usa il ",
  "currencyConverter": "convertitore di valuta",
  "howtoHeading": "Come prenotare",
  "howtoStep1Title": "Choose your unit",
  "howtoStep4": "Safari Tent • Comfort Tent • Garden Cottage • Thatched Chalet",
  "howtoStep2Title": "Decide on the Dates",
  "howtoStep2": "The longer you stay, the better the rate",
  "howtoStep3Title": "Fill in the number of adults/children",
  "howtoStep3": "Max. 2 adults + 1 child or 1 adult and 2 children per unit. Except for the Garden Cottage; max. 2 adults or 1 adult + 1 child",
  "howtoStep4Title": "Click the Book button",
  "childHeading": "Viaggi con bambini",
  "childBabyTitle": "Neonati/Infanti 0-3 anni",
  "childBabyPrice": "Gratis",
  "childBabyBooking": "Non aggiungere durante la prenotazione",
  "childBabyNote": "Aggiungi culla sul modulo di prenotazione se necessario o menzionala nello spazio per note",
  "childChildrenTitle": "Bambini 4-11 anni",
  "childChildrenPrice": "Metà prezzo",
  "childChildrenBooking": "Aggiungi quando scegli il numero di occupanti",
  "childChildrenBed": "Letto Safari extra sarà fornito quando il totale è 3",
  "childYoungsterTitle": "Giovani dai 12 anni in su",
  "childYoungsterPrice": "Contano come adulti",
  "modalTitle": "Perché prenotare direttamente?",
  "modalRate": "Miglior Tariffa Garantita",
  "modalRateDesc": "Prezzi più bassi prenotando direttamente",
  "modalSecure": "Pagamento sicuro",
  "modalSecureDesc": "I tuoi dati sono protetti con crittografia standard",
  "modalNofees": "Nessun costo nascosto",
  "modalNofeesDesc": "Quello che vedi è quello che paghi - prezzi trasparenti",
  "modalInstant": "Conferma immediata",
  "modalInstantDesc": "Ricevi la tua conferma di prenotazione immediatamente",
  "modalSupport": "Supporto del team DEVOCEAN",
  "modalSupportDesc": "Assistenza personale dal nostro team dedicato",
  "units": {
    "safari": "Tenda Safari",
    "comfort": "Tenda Comfort",
    "cottage": "Cottage da Giardino",
    "chalet": "Chalet di Paglia"
  }
};