export default {
  "title": "Prenota il tuo soggiorno – DEVOCEAN Lodge",
  "desc": "Pagina di prenotazione diretta della DEVOCEAN Lodge, Ponta do Ouro, Mozambico. Migliori tariffe, conferma immediata.",
  "home": "Home",
  "back": "Indietro",
  "h1": "Prenota qui al Miglior Prezzo",
  "currencyNote": "Hai bisogno di convertire US$ nella tua valuta? Usa il ",
  "currencyConverter": "convertitore di valuta",
  "howtoHeading": "Come prenotare",
  "howtoStep1Title": "Scegli la tua sistemazione",
  "howtoStep1": "Tenda Safari • Tenda Comfort • Garden Cottage • Chalet di Paglia",
  "howtoStep2Title": "Decidi le date",
  "howtoStep2": "Più a lungo rimani, migliore è la tariffa",
  "howtoStep3Title": "Inserisci il numero di adulti/bambini",
  "howtoStep3": "Max. 2 adulti + 1 bambino o 1 adulto e 2 bambini per unità. Tranne per il Garden Cottage; max. 2 adulti o 1 adulto + 1 bambino",
  "howtoStep4Title": "Clicca su Prenota",
  "howtoStep4": "E compila il modulo",
  "childHeading": "Viaggi con bambini",
  "childBabyTitle": "Neonati/Infanti 0-3 anni",
  "childBabyPrice": "Gratis",
  "childBabyBooking": "Non aggiungere durante la prenotazione",
  "childBabyNote": "Aggiungi culla sul modulo di prenotazione se necessario o menzionala nello spazio per note",
  "childChildrenTitle": "Bambini 4-11 anni",
  "childChildrenPrice": "Metà prezzo",
  "childChildrenBooking": "Aggiungi quando scegli il numero di occupanti",
  "childChildrenBed": "Letto Safari extra sarà fornito quando il totale è 3",
  "childYoungsterTitle": "Giovani dai 12 anni in su",
  "childYoungsterPrice": "Contano come adulti",
  "modalTitle": "Perché prenotare direttamente?",
  "modalRate": "Miglior Tariffa Garantita",
  "modalRateDesc": "Prezzi più bassi prenotando direttamente",
  "modalSecure": "Pagamento sicuro",
  "modalSecureDesc": "I tuoi dati sono protetti con crittografia standard",
  "modalNofees": "Nessun costo nascosto",
  "modalNofeesDesc": "Quello che vedi è quello che paghi - prezzi trasparenti",
  "modalInstant": "Conferma immediata",
  "modalInstantDesc": "Ricevi la tua conferma di prenotazione immediatamente",
  "modalSupport": "Supporto del team DEVOCEAN",
  "modalSupportDesc": "Assistenza personale dal nostro team dedicato",
  "supportTitle": "Benvenuto al Supporto Prenotazioni DEVOCEAN",
  "supportIntro": "Il nostro team è pronto ad aiutarti con:",
  "supportHelp1": "Scegliere la sistemazione giusta",
  "supportHelp2": "Comprendere disponibilità e tariffe",
  "supportHelp3": "Richieste speciali",
  "supportHours": "Orari di apertura:",
  "supportHoursTime": "Lunedì-Domenica, 8:00-17:00 CAT",
  "supportButton": "Chatta su WhatsApp",
  "units": {
    "safari": "Tenda Safari",
    "comfort": "Tenda Comfort",
    "cottage": "Cottage da Giardino",
    "chalet": "Chalet di Paglia"
  }
};