export default {
  "title": "ご宿泊予約 – DEVOCEAN Lodge",
  "desc": "DEVOCEAN Lodge（モザンビーク・ポンタ・ド・オウロ）の公式直予約ページ。最安値・即時確認。",
  "home": "ホーム",
  "back": "戻る",
  "h1": "ベストプライスでここから予約",
  "currencyNote": "US$をあなたの通貨に換算する必要がありますか？",
  "currencyConverter": "通貨換算",
  "howtoHeading": "予約方法",
  "howtoStep1Title": "Choose your unit",
  "howtoStep4": "Safari Tent • Comfort Tent • Garden Cottage • Thatched Chalet",
  "howtoStep2Title": "Decide on the Dates",
  "howtoStep2": "The longer you stay, the better the rate",
  "howtoStep3Title": "Fill in the number of adults/children",
  "howtoStep3": "Max. 2 adults + 1 child or 1 adult and 2 children per unit. Except for the Garden Cottage; max. 2 adults or 1 adult + 1 child",
  "howtoStep4Title": "Click the Book button",
  "childHeading": "お子様連れですか",
  "childBabyTitle": "乳幼児 0-3歳",
  "childBabyPrice": "無料",
  "childBabyBooking": "予約時に追加しないでください",
  "childBabyNote": "必要に応じて予約フォームでベビーベッドを追加するか、備考欄に記載してください",
  "childChildrenTitle": "お子様 4-11歳",
  "childChildrenPrice": "半額",
  "childChildrenBooking": "宿泊人数を選択する際に追加",
  "childChildrenBed": "合計が3名の場合、追加のSafariベッドを提供",
  "childYoungsterTitle": "12歳以上の若者",
  "childYoungsterPrice": "大人としてカウント",
  "modalTitle": "直接予約のメリット",
  "modalRate": "最優遇料金保証",
  "modalRateDesc": "直接予約で最安値をご提供",
  "modalSecure": "安全な決済",
  "modalSecureDesc": "業界標準の暗号化でデータを保護",
  "modalNofees": "追加料金なし",
  "modalNofeesDesc": "表示価格が支払額 - 透明な料金体系",
  "modalInstant": "即時確認",
  "modalInstantDesc": "予約確認を即座に受信",
  "modalSupport": "DEVOCEANチームサポート",
  "modalSupportDesc": "専任チームによる個別サポート",
  "units": {
    "safari": "サファリテント",
    "comfort": "コンフォートテント",
    "cottage": "ガーデンコテージ",
    "chalet": "サッチシャレ"
  }
};