export default {
  "title": "ご宿泊予約 – DEVOCEAN Lodge",
  "desc": "DEVOCEAN Lodge（モザンビーク・ポンタ・ド・オウロ）の公式直予約ページ。最安値・即時確認。",
  "home": "ホーム",
  "back": "戻る",
  "h1": "ベストプライスでここから予約",
  "currencyNote": "US$をあなたの通貨に換算する必要がありますか？",
  "currencyConverter": "通貨換算",
  "howtoHeading": "予約方法",
  "howtoStep1Title": "宿泊施設を選択",
  "howtoStep1": "サファリテント • コンフォートテント • ガーデンコテージ • 茅葺きシャレー",
  "howtoStep2Title": "日付を決定",
  "howtoStep2": "滞在が長いほどお得な料金",
  "howtoStep3Title": "大人/子供の人数を入力",
  "howtoStep3": "1ユニットあたり最大2名の大人+1名の子供、または1名の大人と2名の子供。ガーデンコテージを除く；最大2名の大人または1名の大人+1名の子供",
  "howtoStep4Title": "予約ボタンをクリック",
  "howtoStep4": "フォームに記入してください",
  "childHeading": "お子様連れですか",
  "childBabyTitle": "乳幼児 0-3歳",
  "childBabyPrice": "無料",
  "childBabyBooking": "予約時に追加しないでください",
  "childBabyNote": "必要に応じて予約フォームでベビーベッドを追加するか、備考欄に記載してください",
  "childChildrenTitle": "お子様 4-11歳",
  "childChildrenPrice": "半額",
  "childChildrenBooking": "宿泊人数を選択する際に追加",
  "childChildrenBed": "合計が3名の場合、追加のSafariベッドを提供",
  "childYoungsterTitle": "12歳以上の若者",
  "childYoungsterPrice": "大人としてカウント",
  "modalTitle": "直接予約のメリット",
  "modalRate": "最優遇料金保証",
  "modalRateDesc": "直接予約で最安値をご提供",
  "modalSecure": "安全な決済",
  "modalSecureDesc": "業界標準の暗号化でデータを保護",
  "modalNofees": "追加料金なし",
  "modalNofeesDesc": "表示価格が支払額 - 透明な料金体系",
  "modalInstant": "即時確認",
  "modalInstantDesc": "予約確認を即座に受信",
  "modalSupport": "DEVOCEANチームサポート",
  "modalSupportDesc": "専任チームによる個別サポート",
  "supportTitle": "DEVOCEAN予約サポートへようこそ",
  "supportIntro": "当チームがお手伝いできること：",
  "supportHelp1": "最適な宿泊施設の選択",
  "supportHelp2": "空室状況と料金の理解",
  "supportHelp3": "特別なリクエスト",
  "supportHours": "営業時間：",
  "supportHoursTime": "月曜日～日曜日、8:00-17:00 CAT",
  "supportButton": "WhatsAppでチャット",
  "units": {
    "safari": "サファリテント",
    "comfort": "コンフォートテント",
    "cottage": "ガーデンコテージ",
    "chalet": "サッチシャレ"
  }
};