export default {
  "title": "Boek uw verblijf – DEVOCEAN Lodge",
  "desc": "Directe boekingspagina van DEVOCEAN Lodge, Ponta do Ouro, Mozambique. Beste prijzen, directe bevestiging.",
  "home": "Home",
  "back": "Terug",
  "h1": "Boek hier voor Beste Prijs",
  "currencyNote": "Moet u US$ omrekenen naar uw valuta? Gebruik de ",
  "currencyConverter": "valutaconverter",
  "howtoHeading": "Hoe te boeken",
  "howtoStep1Title": "Kies uw accommodatie",
  "howtoStep1": "Safari Tent • Comfort Tent • Garden Cottage • Rieten Chalet",
  "howtoStep2Title": "Bepaal de data",
  "howtoStep2": "Hoe langer u blijft, hoe beter het tarief",
  "howtoStep3Title": "Vul het aantal volwassenen/kinderen in",
  "howtoStep3": "Max. 2 volwassenen + 1 kind of 1 volwassene en 2 kinderen per eenheid. Behalve voor de Garden Cottage; max. 2 volwassenen of 1 volwassene + 1 kind",
  "howtoStep4Title": "Klik op Boeken",
  "howtoStep4": "En vul het formulier in",
  "childHeading": "Reist u met kinderen",
  "childBabyTitle": "Baby's/Peuters 0-3 jaar",
  "childBabyPrice": "Gratis",
  "childBabyBooking": "Niet toevoegen tijdens boeking",
  "childBabyNote": "Voeg babybedje toe op het boekingsformulier indien nodig of vermeld in de ruimte voor notities",
  "childChildrenTitle": "Kinderen 4-11 jaar",
  "childChildrenPrice": "Halve prijs",
  "childChildrenBooking": "Voeg toe bij het kiezen van aantal bezoekers",
  "childChildrenBed": "Extra Safari bed wordt verstrekt wanneer totaal 3 is",
  "childYoungsterTitle": "Jongeren vanaf 12 jaar",
  "childYoungsterPrice": "Tellen als volwassenen",
  "modalTitle": "Waarom direct boeken?",
  "modalRate": "Beste Prijs Gegarandeerd",
  "modalRateDesc": "Laagste prijzen bij directe boeking",
  "modalSecure": "Veilige betaling",
  "modalSecureDesc": "Uw gegevens zijn beschermd met standaard versleuteling",
  "modalNofees": "Geen verborgen kosten",
  "modalNofeesDesc": "Wat u ziet is wat u betaalt - transparante prijzen",
  "modalInstant": "Directe bevestiging",
  "modalInstantDesc": "Ontvang uw boekingsbevestiging onmiddellijk",
  "modalSupport": "DEVOCEAN Team ondersteuning",
  "modalSupportDesc": "Persoonlijke hulp van ons toegewijde team",
  "units": {
    "safari": "Safari Tent",
    "comfort": "Comfort Tent",
    "cottage": "Tuin Cottage",
    "chalet": "Rieten Chalet"
  }
};