export default {
  "title": "Boek uw verblijf – DEVOCEAN Lodge",
  "desc": "Directe boekingspagina van DEVOCEAN Lodge, Ponta do Ouro, Mozambique. Beste prijzen, directe bevestiging.",
  "home": "Home",
  "back": "Terug",
  "h1": "Boek hier voor Beste Prijs",
  "currencyNote": "Moet u US$ omrekenen naar uw valuta? Gebruik de ",
  "currencyConverter": "valutaconverter",
  "howtoHeading": "Hoe te boeken",
  "howtoStep1Title": "Choose your unit",
  "howtoStep4": "Safari Tent • Comfort Tent • Garden Cottage • Thatched Chalet",
  "howtoStep2Title": "Decide on the Dates",
  "howtoStep2": "The longer you stay, the better the rate",
  "howtoStep3Title": "Fill in the number of adults/children",
  "howtoStep3": "Max. 2 adults + 1 child or 1 adult and 2 children per unit. Except for the Garden Cottage; max. 2 adults or 1 adult + 1 child",
  "howtoStep4Title": "Click the Book button",
  "childHeading": "Reist u met kinderen",
  "childBabyTitle": "Baby's/Peuters 0-3 jaar",
  "childBabyPrice": "Gratis",
  "childBabyBooking": "Niet toevoegen tijdens boeking",
  "childBabyNote": "Voeg babybedje toe op het boekingsformulier indien nodig of vermeld in de ruimte voor notities",
  "childChildrenTitle": "Kinderen 4-11 jaar",
  "childChildrenPrice": "Halve prijs",
  "childChildrenBooking": "Voeg toe bij het kiezen van aantal bezoekers",
  "childChildrenBed": "Extra Safari bed wordt verstrekt wanneer totaal 3 is",
  "childYoungsterTitle": "Jongeren vanaf 12 jaar",
  "childYoungsterPrice": "Tellen als volwassenen",
  "modalTitle": "Waarom direct boeken?",
  "modalRate": "Beste Prijs Gegarandeerd",
  "modalRateDesc": "Laagste prijzen bij directe boeking",
  "modalSecure": "Veilige betaling",
  "modalSecureDesc": "Uw gegevens zijn beschermd met standaard versleuteling",
  "modalNofees": "Geen verborgen kosten",
  "modalNofeesDesc": "Wat u ziet is wat u betaalt - transparante prijzen",
  "modalInstant": "Directe bevestiging",
  "modalInstantDesc": "Ontvang uw boekingsbevestiging onmiddellijk",
  "modalSupport": "DEVOCEAN Team ondersteuning",
  "modalSupportDesc": "Persoonlijke hulp van ons toegewijde team",
  "units": {
    "safari": "Safari Tent",
    "comfort": "Comfort Tent",
    "cottage": "Tuin Cottage",
    "chalet": "Rieten Chalet"
  }
};