export default {
  "title": "Zarezerwuj swój pobyt – DEVOCEAN Lodge",
  "desc": "Strona rezerwacji bezpośredniej DEVOCEAN Lodge, Ponta do Ouro, Mozambik. Najlepsze ceny, natychmiastowe potwierdzenie.",
  "home": "Strona główna",
  "back": "Wstecz",
  "h1": "Rezerwuj tutaj po Najlepszej Cenie",
  "currencyNote": "Potrzebujesz przeliczyć US$ na swoją walutę? Użyj ",
  "currencyConverter": "przelicznika walut",
  "howtoHeading": "Jak zarezerwować",
  "howtoStep1Title": "Wybierz zakwaterowanie",
  "howtoStep1": "Namiot Safari • Namiot Comfort • Domek Ogrodowy • Chata Kryta Strzechą",
  "howtoStep2Title": "Wybierz daty",
  "howtoStep2": "Im dłużej zostaniesz, tym lepsza cena",
  "howtoStep3Title": "Wpisz liczbę dorosłych/dzieci",
  "howtoStep3": "Maks. 2 dorosłych + 1 dziecko lub 1 dorosły i 2 dzieci na jednostkę. Z wyjątkiem Garden Cottage; maks. 2 dorosłych lub 1 dorosły + 1 dziecko",
  "howtoStep4Title": "Kliknij Zarezerwuj",
  "howtoStep4": "I wypełnij formularz",
  "childHeading": "Podróżujesz z dziećmi",
  "childBabyTitle": "Niemowlęta 0-3 lata",
  "childBabyPrice": "Bezpłatnie",
  "childBabyBooking": "Nie dodawaj podczas rezerwacji",
  "childBabyNote": "Dodaj łóżeczko dziecięce w formularzu rezerwacji w razie potrzeby lub wspomnij w polu notatki",
  "childChildrenTitle": "Dzieci 4-11 lat",
  "childChildrenPrice": "Pół ceny",
  "childChildrenBooking": "Dodaj przy wyborze liczby gości",
  "childChildrenBed": "Dodatkowe łóżko Safari zostanie dostarczone, gdy suma wynosi 3",
  "childYoungsterTitle": "Młodzież od 12 lat",
  "childYoungsterPrice": "Liczą się jako dorośli",
  "modalTitle": "Dlaczego rezerwować bezpośrednio?",
  "modalRate": "Najlepsza Cena Gwarantowana",
  "modalRateDesc": "Najniższe ceny przy bezpośredniej rezerwacji",
  "modalSecure": "Bezpieczna płatność",
  "modalSecureDesc": "Twoje dane są chronione standardowym szyfrowaniem",
  "modalNofees": "Bez ukrytych opłat",
  "modalNofeesDesc": "Co widzisz, to płacisz - przejrzyste ceny",
  "modalInstant": "Natychmiastowe potwierdzenie",
  "modalInstantDesc": "Otrzymaj potwierdzenie rezerwacji natychmiast",
  "modalSupport": "Wsparcie zespołu DEVOCEAN",
  "modalSupportDesc": "Osobista pomoc od naszego dedykowanego zespołu",
  "supportTitle": "Witaj w Wsparciu Rezerwacji DEVOCEAN",
  "supportIntro": "Nasz zespół jest gotowy pomóc Ci z:",
  "supportHelp1": "Wyborem odpowiedniego zakwaterowania",
  "supportHelp2": "Zrozumieniem dostępności i cen",
  "supportHelp3": "Specjalnymi życzeniami",
  "supportHours": "Godziny otwarcia:",
  "supportHoursTime": "Poniedziałek-Niedziela, 8:00-17:00 CAT",
  "supportButton": "Czat na WhatsApp",
  "units": {
    "safari": "Namiot Safari",
    "comfort": "Namiot Comfort",
    "cottage": "Domek Ogrodowy",
    "chalet": "Chata ze Strzechy"
  }
};