export default {
  "title": "Zarezerwuj swój pobyt – DEVOCEAN Lodge",
  "desc": "Strona rezerwacji bezpośredniej DEVOCEAN Lodge, Ponta do Ouro, Mozambik. Najlepsze ceny, natychmiastowe potwierdzenie.",
  "home": "Strona główna",
  "back": "Wstecz",
  "h1": "Rezerwuj tutaj po Najlepszej Cenie",
  "currencyNote": "Potrzebujesz przeliczyć US$ na swoją walutę? Użyj ",
  "currencyConverter": "przelicznika walut",
  "howtoHeading": "Jak zarezerwować",
  "howtoStep1Title": "Choose your unit",
  "howtoStep4": "Safari Tent • Comfort Tent • Garden Cottage • Thatched Chalet",
  "howtoStep2Title": "Decide on the Dates",
  "howtoStep2": "The longer you stay, the better the rate",
  "howtoStep3Title": "Fill in the number of adults/children",
  "howtoStep3": "Max. 2 adults + 1 child or 1 adult and 2 children per unit. Except for the Garden Cottage; max. 2 adults or 1 adult + 1 child",
  "howtoStep4Title": "Click the Book button",
  "childHeading": "Podróżujesz z dziećmi",
  "childBabyTitle": "Niemowlęta 0-3 lata",
  "childBabyPrice": "Bezpłatnie",
  "childBabyBooking": "Nie dodawaj podczas rezerwacji",
  "childBabyNote": "Dodaj łóżeczko dziecięce w formularzu rezerwacji w razie potrzeby lub wspomnij w polu notatki",
  "childChildrenTitle": "Dzieci 4-11 lat",
  "childChildrenPrice": "Pół ceny",
  "childChildrenBooking": "Dodaj przy wyborze liczby gości",
  "childChildrenBed": "Dodatkowe łóżko Safari zostanie dostarczone, gdy suma wynosi 3",
  "childYoungsterTitle": "Młodzież od 12 lat",
  "childYoungsterPrice": "Liczą się jako dorośli",
  "modalTitle": "Dlaczego rezerwować bezpośrednio?",
  "modalRate": "Najlepsza Cena Gwarantowana",
  "modalRateDesc": "Najniższe ceny przy bezpośredniej rezerwacji",
  "modalSecure": "Bezpieczna płatność",
  "modalSecureDesc": "Twoje dane są chronione standardowym szyfrowaniem",
  "modalNofees": "Bez ukrytych opłat",
  "modalNofeesDesc": "Co widzisz, to płacisz - przejrzyste ceny",
  "modalInstant": "Natychmiastowe potwierdzenie",
  "modalInstantDesc": "Otrzymaj potwierdzenie rezerwacji natychmiast",
  "modalSupport": "Wsparcie zespołu DEVOCEAN",
  "modalSupportDesc": "Osobista pomoc od naszego dedykowanego zespołu",
  "units": {
    "safari": "Namiot Safari",
    "comfort": "Namiot Comfort",
    "cottage": "Domek Ogrodowy",
    "chalet": "Chata ze Strzechy"
  }
};