export default {
  "title": "Reserve a sua estadia – DEVOCEAN Lodge",
  "desc": "Página de reserva direta da DEVOCEAN Lodge, Ponta do Ouro, Moçambique. Melhores tarifas, confirmação imediata.",
  "home": "Início",
  "back": "Voltar",
  "h1": "Reserve aqui pelo Melhor Preço",
  "currencyNote": "Precisa de converter US$ para a sua moeda? Use o ",
  "currencyConverter": "conversor de moeda",
  "howtoHeading": "Como reservar",
  "howtoStep1Title": "Escolha sua acomodação",
  "howtoStep1": "Tenda Safari • Tenda Comfort • Cottage de Jardim • Chalé de Palha",
  "howtoStep2Title": "Decida as datas",
  "howtoStep2": "Quanto mais tempo ficar, melhor a tarifa",
  "howtoStep3Title": "Preencha o número de adultos/crianças",
  "howtoStep3": "Máx. 2 adultos + 1 criança ou 1 adulto e 2 crianças por unidade. Exceto para o Garden Cottage; máx. 2 adultos ou 1 adulto + 1 criança",
  "howtoStep4Title": "Clique em Reservar",
  "howtoStep4": "E preencha o formulário",
  "childHeading": "Viaja com crianças",
  "childBabyTitle": "Bebés/Infantis 0-3 anos",
  "childBabyPrice": "Grátis",
  "childBabyBooking": "Não adicione durante a reserva",
  "childBabyNote": "Adicione berço no formulário de reserva se necessário ou mencione no espaço para notas",
  "childChildrenTitle": "Crianças 4-11 anos",
  "childChildrenPrice": "Metade do preço",
  "childChildrenBooking": "Adicione ao escolher o número de ocupantes",
  "childChildrenBed": "Cama Safari extra será fornecida quando o total for 3",
  "childYoungsterTitle": "Jovens a partir dos 12 anos",
  "childYoungsterPrice": "Contam como adultos",
  "modalTitle": "Porquê reservar diretamente?",
  "modalRate": "Melhor Tarifa Garantida",
  "modalRateDesc": "Preços mais baixos ao reservar diretamente",
  "modalSecure": "Pagamento seguro",
  "modalSecureDesc": "Os seus dados estão protegidos com encriptação padrão",
  "modalNofees": "Sem custos ocultos",
  "modalNofeesDesc": "O que vê é o que paga - preços transparentes",
  "modalInstant": "Confirmação imediata",
  "modalInstantDesc": "Receba a sua confirmação de reserva imediatamente",
  "modalSupport": "Apoio da equipa DEVOCEAN",
  "modalSupportDesc": "Assistência pessoal da nossa equipa dedicada",
  "units": {
    "safari": "Tenda Safari",
    "comfort": "Tenda Comfort",
    "cottage": "Cottage de Jardim",
    "chalet": "Chalé de Palha"
  }
};