export default {
  "title": "Reserve a sua estadia – DEVOCEAN Lodge",
  "desc": "Página de reserva direta da DEVOCEAN Lodge, Ponta do Ouro, Moçambique. Melhores tarifas, confirmação imediata.",
  "home": "Início",
  "back": "Voltar",
  "h1": "Reserve aqui pelo Melhor Preço",
  "currencyNote": "Precisa de converter US$ para a sua moeda? Use o ",
  "currencyConverter": "conversor de moeda",
  "howtoHeading": "Como reservar",
  "howtoStep1Title": "Choose your unit",
  "howtoStep4": "Safari Tent • Comfort Tent • Garden Cottage • Thatched Chalet",
  "howtoStep2Title": "Decide on the Dates",
  "howtoStep2": "The longer you stay, the better the rate",
  "howtoStep3Title": "Fill in the number of adults/children",
  "howtoStep3": "Max. 2 adults + 1 child or 1 adult and 2 children per unit. Except for the Garden Cottage; max. 2 adults or 1 adult + 1 child",
  "howtoStep4Title": "Click the Book button",
  "childHeading": "Viaja com crianças",
  "childBabyTitle": "Bebés/Infantis 0-3 anos",
  "childBabyPrice": "Grátis",
  "childBabyBooking": "Não adicione durante a reserva",
  "childBabyNote": "Adicione berço no formulário de reserva se necessário ou mencione no espaço para notas",
  "childChildrenTitle": "Crianças 4-11 anos",
  "childChildrenPrice": "Metade do preço",
  "childChildrenBooking": "Adicione ao escolher o número de ocupantes",
  "childChildrenBed": "Cama Safari extra será fornecida quando o total for 3",
  "childYoungsterTitle": "Jovens a partir dos 12 anos",
  "childYoungsterPrice": "Contam como adultos",
  "modalTitle": "Porquê reservar diretamente?",
  "modalRate": "Melhor Tarifa Garantida",
  "modalRateDesc": "Preços mais baixos ao reservar diretamente",
  "modalSecure": "Pagamento seguro",
  "modalSecureDesc": "Os seus dados estão protegidos com encriptação padrão",
  "modalNofees": "Sem custos ocultos",
  "modalNofeesDesc": "O que vê é o que paga - preços transparentes",
  "modalInstant": "Confirmação imediata",
  "modalInstantDesc": "Receba a sua confirmação de reserva imediatamente",
  "modalSupport": "Apoio da equipa DEVOCEAN",
  "modalSupportDesc": "Assistência pessoal da nossa equipa dedicada",
  "units": {
    "safari": "Tenda Safari",
    "comfort": "Tenda Comfort",
    "cottage": "Cottage de Jardim",
    "chalet": "Chalé de Palha"
  }
};