export default {
  "title": "Забронируйте проживание – DEVOCEAN Lodge",
  "desc": "Страница прямого бронирования DEVOCEAN Lodge (Понта-ду-Ору, Мозамбик). Лучшие цены, мгновенное подтверждение.",
  "home": "Главная",
  "back": "Назад",
  "h1": "Бронируйте здесь по Лучшей Цене",
  "currencyNote": "Нужно конвертировать US$ в вашу валюту? Используйте ",
  "currencyConverter": "конвертер валют",
  "howtoHeading": "Как забронировать",
  "howtoStep1Title": "Choose your unit",
  "howtoStep4": "Safari Tent • Comfort Tent • Garden Cottage • Thatched Chalet",
  "howtoStep2Title": "Decide on the Dates",
  "howtoStep2": "The longer you stay, the better the rate",
  "howtoStep3Title": "Fill in the number of adults/children",
  "howtoStep3": "Max. 2 adults + 1 child or 1 adult and 2 children per unit. Except for the Garden Cottage; max. 2 adults or 1 adult + 1 child",
  "howtoStep4Title": "Click the Book button",
  "childHeading": "Путешествуете с детьми",
  "childBabyTitle": "Младенцы 0-3 года",
  "childBabyPrice": "Бесплатно",
  "childBabyBooking": "Не добавляйте при бронировании",
  "childBabyNote": "Добавьте детскую кроватку в форме бронирования при необходимости или упомяните в поле для заметок",
  "childChildrenTitle": "Дети 4-11 лет",
  "childChildrenPrice": "Половина цены",
  "childChildrenBooking": "Добавьте при выборе количества гостей",
  "childChildrenBed": "Дополнительная кровать Safari будет предоставлена, когда общее количество равно 3",
  "childYoungsterTitle": "Подростки от 12 лет",
  "childYoungsterPrice": "Считаются взрослыми",
  "modalTitle": "Почему бронировать напрямую?",
  "modalRate": "Лучшая Цена Гарантирована",
  "modalRateDesc": "Самые низкие цены при прямом бронировании",
  "modalSecure": "Безопасный платеж",
  "modalSecureDesc": "Ваши данные защищены стандартным шифрованием",
  "modalNofees": "Без скрытых сборов",
  "modalNofeesDesc": "Что видите, то и платите - прозрачные цены",
  "modalInstant": "Мгновенное подтверждение",
  "modalInstantDesc": "Получите подтверждение бронирования немедленно",
  "modalSupport": "Поддержка команды DEVOCEAN",
  "modalSupportDesc": "Персональная помощь от нашей команды",
  "units": {
    "safari": "Палатка Сафари",
    "comfort": "Палатка Комфорт",
    "cottage": "Садовый Коттедж",
    "chalet": "Соломенный Шале"
  }
};