export default {
  "title": "Boka din vistelse – DEVOCEAN Lodge",
  "desc": "Direktbokningssida för DEVOCEAN Lodge, Ponta do Ouro, Moçambique. Bästa priser, omedelbar bekräftelse.",
  "home": "Hem",
  "back": "Tillbaka",
  "h1": "Boka här för Bästa Pris",
  "currencyNote": "Behöver du konvertera US$ till din valuta? Använd ",
  "currencyConverter": "valutaomvandlare",
  "howtoHeading": "Hur man bokar",
  "howtoStep1Title": "Välj din bostad",
  "howtoStep1": "Safari Tält • Comfort Tält • Trädgårdsstuga • Halmtak Chalet",
  "howtoStep2Title": "Bestäm datum",
  "howtoStep2": "Ju längre du stannar, desto bättre pris",
  "howtoStep3Title": "Fyll i antal vuxna/barn",
  "howtoStep3": "Max. 2 vuxna + 1 barn eller 1 vuxen och 2 barn per enhet. Förutom för Garden Cottage; max. 2 vuxna eller 1 vuxen + 1 barn",
  "howtoStep4Title": "Klicka på Boka",
  "howtoStep4": "Och fyll i formuläret",
  "childHeading": "Reser du med barn",
  "childBabyTitle": "Spädbarn 0-3 år",
  "childBabyPrice": "Gratis",
  "childBabyBooking": "Lägg inte till vid bokning",
  "childBabyNote": "Lägg till spjälsäng på bokningsformuläret om det behövs eller nämn i utrymme för anteckning",
  "childChildrenTitle": "Barn 4-11 år",
  "childChildrenPrice": "Halv pris",
  "childChildrenBooking": "Lägg till när du väljer antal gäster",
  "childChildrenBed": "Extra Safari-säng kommer att tillhandahållas när totalen är 3",
  "childYoungsterTitle": "Ungdomar från 12 år",
  "childYoungsterPrice": "Räknas som vuxna",
  "modalTitle": "Varför boka direkt?",
  "modalRate": "Bästa Pris Garanterat",
  "modalRateDesc": "Lägsta priser när du bokar direkt",
  "modalSecure": "Säker betalning",
  "modalSecureDesc": "Dina uppgifter skyddas med branschstandard kryptering",
  "modalNofees": "Inga dolda avgifter",
  "modalNofeesDesc": "Vad du ser är vad du betalar - transparenta priser",
  "modalInstant": "Omedelbar bekräftelse",
  "modalInstantDesc": "Få din bokningsbekräftelse omedelbart",
  "modalSupport": "DEVOCEAN Team-support",
  "modalSupportDesc": "Personlig hjälp från vårt dedikerade team",
  "supportTitle": "Välkommen till DEVOCEAN Bokningssupport",
  "supportIntro": "Vårt team är redo att hjälpa dig med:",
  "supportHelp1": "Välja rätt boende",
  "supportHelp2": "Förstå tillgänglighet och priser",
  "supportHelp3": "Särskilda önskemål",
  "supportHours": "Öppettider:",
  "supportHoursTime": "Måndag-Söndag, 8:00-17:00 CAT",
  "supportButton": "Chatta på WhatsApp",
  "units": {
    "safari": "Safari Tält",
    "comfort": "Comfort Tält",
    "cottage": "Trädgård Cottage",
    "chalet": "Stråtak Chalet"
  }
};