export default {
  "title": "Weka nafasi yako ya kukaa – DEVOCEAN Lodge",
  "desc": "Ukurasa wa kuweka nafasi moja kwa moja wa DEVOCEAN Lodge, Ponta do Ouro, Msumbiji. Bei bora, uthibitisho wa haraka.",
  "home": "Nyumbani",
  "back": "Rudi",
  "h1": "Weka nafasi hapa kwa Bei Bora",
  "currencyNote": "Unahitaji kubadilisha US$ kuwa sarafu yako? Tumia ",
  "currencyConverter": "kibadilishaji cha sarafu",
  "howtoHeading": "Jinsi ya kuweka nafasi",
  "howtoStep1Title": "Choose your unit",
  "howtoStep4": "Safari Tent • Comfort Tent • Garden Cottage • Thatched Chalet",
  "howtoStep2Title": "Decide on the Dates",
  "howtoStep2": "The longer you stay, the better the rate",
  "howtoStep3Title": "Fill in the number of adults/children",
  "howtoStep3": "Max. 2 adults + 1 child or 1 adult and 2 children per unit. Except for the Garden Cottage; max. 2 adults or 1 adult + 1 child",
  "howtoStep4Title": "Click the Book button",
  "childHeading": "Unasafiri na watoto",
  "childBabyTitle": "Watoto wachanga 0-3 miaka",
  "childBabyPrice": "Bure",
  "childBabyBooking": "Usiongeze wakati wa kuweka nafasi",
  "childBabyNote": "Ongeza kitanda cha mtoto mchanga kwenye fomu ya kuhifadhi ikiwa inahitajika au taja katika nafasi ya kumbukumbu",
  "childChildrenTitle": "Watoto 4-11 miaka",
  "childChildrenPrice": "Nusu Bei",
  "childChildrenBooking": "Ongeza unapochagua idadi ya wakazi",
  "childChildrenBed": "Kitanda cha ziada cha Safari kitatolewa wakati jumla ni 3",
  "childYoungsterTitle": "Vijana kuanzia miaka 12",
  "childYoungsterPrice": "Wanahesabiwa kama watu wazima",
  "modalTitle": "Kwa nini uweke nafasi moja kwa moja?",
  "modalRate": "Bei Bora Imethibitishwa",
  "modalRateDesc": "Bei za chini zaidi unapoweka nafasi moja kwa moja",
  "modalSecure": "Malipo salama",
  "modalSecureDesc": "Data yako inalindwa kwa usimbaji fiche wa kiwango cha sekta",
  "modalNofees": "Hakuna gharama zilizoficha",
  "modalNofeesDesc": "Unachokiona ndivyo unacholipa - bei wazi",
  "modalInstant": "Uthibitisho wa haraka",
  "modalInstantDesc": "Pokea uthibitisho wako wa uhifadhi mara moja",
  "modalSupport": "Msaada wa timu ya DEVOCEAN",
  "modalSupportDesc": "Msaada wa kibinafsi kutoka kwa timu yetu iliyojitolea",
  "units": {
    "safari": "Hema ya Safari",
    "comfort": "Hema ya Comfort",
    "cottage": "Cottage ya Bustani",
    "chalet": "Chalet ya Nyasi"
  }
};