export default {
  "title": "Weka nafasi yako ya kukaa – DEVOCEAN Lodge",
  "desc": "Ukurasa wa kuweka nafasi moja kwa moja wa DEVOCEAN Lodge, Ponta do Ouro, Msumbiji. Bei bora, uthibitisho wa haraka.",
  "home": "Nyumbani",
  "back": "Rudi",
  "h1": "Weka nafasi hapa kwa Bei Bora",
  "currencyNote": "Unahitaji kubadilisha US$ kuwa sarafu yako? Tumia ",
  "currencyConverter": "kibadilishaji cha sarafu",
  "howtoHeading": "Jinsi ya kuweka nafasi",
  "howtoStep1Title": "Chagua kipimo chako",
  "howtoStep1": "Hema ya Safari • Hema ya Comfort • Nyumba ya Bustani • Chalet ya Majani",
  "howtoStep2Title": "Amua tarehe",
  "howtoStep2": "Kadiri unavyokaa kwa muda mrefu, bei inakuwa bora zaidi",
  "howtoStep3Title": "Jaza idadi ya wazima/watoto",
  "howtoStep3": "Juu. watu wazima 2 + mtoto 1 au mtu mzima 1 na watoto 2 kwa kila kipimo. Isipokuwa Garden Cottage; juu. watu wazima 2 au mtu mzima 1 + mtoto 1",
  "howtoStep4Title": "Bonyeza Hifadhi",
  "howtoStep4": "Na ujaze fomu",
  "childHeading": "Unasafiri na watoto",
  "childBabyTitle": "Watoto wachanga 0-3 miaka",
  "childBabyPrice": "Bure",
  "childBabyBooking": "Usiongeze wakati wa kuweka nafasi",
  "childBabyNote": "Ongeza kitanda cha mtoto mchanga kwenye fomu ya kuhifadhi ikiwa inahitajika au taja katika nafasi ya kumbukumbu",
  "childChildrenTitle": "Watoto 4-11 miaka",
  "childChildrenPrice": "Nusu Bei",
  "childChildrenBooking": "Ongeza unapochagua idadi ya wakazi",
  "childChildrenBed": "Kitanda cha ziada cha Safari kitatolewa wakati jumla ni 3",
  "childYoungsterTitle": "Vijana kuanzia miaka 12",
  "childYoungsterPrice": "Wanahesabiwa kama watu wazima",
  "modalTitle": "Kwa nini uweke nafasi moja kwa moja?",
  "modalRate": "Bei Bora Imethibitishwa",
  "modalRateDesc": "Bei za chini zaidi unapoweka nafasi moja kwa moja",
  "modalSecure": "Malipo salama",
  "modalSecureDesc": "Data yako inalindwa kwa usimbaji fiche wa kiwango cha sekta",
  "modalNofees": "Hakuna gharama zilizoficha",
  "modalNofeesDesc": "Unachokiona ndivyo unacholipa - bei wazi",
  "modalInstant": "Uthibitisho wa haraka",
  "modalInstantDesc": "Pokea uthibitisho wako wa uhifadhi mara moja",
  "modalSupport": "Msaada wa timu ya DEVOCEAN",
  "modalSupportDesc": "Msaada wa kibinafsi kutoka kwa timu yetu iliyojitolea",
  "units": {
    "safari": "Hema ya Safari",
    "comfort": "Hema ya Comfort",
    "cottage": "Cottage ya Bustani",
    "chalet": "Chalet ya Nyasi"
  }
};