export default {
  "title": "预订您的住宿 – DEVOCEAN Lodge",
  "desc": "DEVOCEAN Lodge（莫桑比克蓬塔杜奥鲁）官方直订页面。最优价格，即时确认。",
  "home": "首页",
  "back": "返回",
  "h1": "在此预订享最优价格",
  "currencyNote": "需要将US$转换为您的货币？使用",
  "currencyConverter": "货币转换器",
  "howtoHeading": "如何预订",
  "howtoStep1Title": "选择您的住宿",
  "howtoStep1": "野生动物帐篷 • 舒适帐篷 • 花园小屋 • 茅草小木屋",
  "howtoStep2Title": "选择日期",
  "howtoStep2": "住得越久，价格越优惠",
  "howtoStep3Title": "填写成人/儿童人数",
  "howtoStep3": "每间最多2名成人+1名儿童或1名成人和2名儿童。花园小屋除外；最多2名成人或1名成人+1名儿童",
  "howtoStep4Title": "点击预订按钮",
  "howtoStep4": "并填写表格",
  "childHeading": "带儿童旅行",
  "childBabyTitle": "婴儿 0-3岁",
  "childBabyPrice": "免费",
  "childBabyBooking": "预订时不要添加",
  "childBabyNote": "如需要，请在预订表格上添加婴儿床或在备注栏中提及",
  "childChildrenTitle": "儿童 4-11岁",
  "childChildrenPrice": "半价",
  "childChildrenBooking": "选择入住人数时添加",
  "childChildrenBed": "总人数为3时将提供额外的Safari床",
  "childYoungsterTitle": "12岁及以上青少年",
  "childYoungsterPrice": "按成人计算",
  "modalTitle": "为何直接预订？",
  "modalRate": "最优价格保证",
  "modalRateDesc": "直接预订享受最低价格",
  "modalSecure": "安全支付",
  "modalSecureDesc": "您的数据受行业标准加密保护",
  "modalNofees": "无隐藏费用",
  "modalNofeesDesc": "所见即所付 - 价格透明",
  "modalInstant": "即时确认",
  "modalInstantDesc": "立即收到您的预订确认",
  "modalSupport": "DEVOCEAN团队支持",
  "modalSupportDesc": "我们专业团队提供个性化协助",
  "units": {
    "safari": "Safari 帐篷",
    "comfort": "舒适帐篷",
    "cottage": "花园小屋",
    "chalet": "茅草木屋"
  }
};