export default {
  "title": "预订您的住宿 – DEVOCEAN Lodge",
  "desc": "DEVOCEAN Lodge（莫桑比克蓬塔杜奥鲁）官方直订页面。最优价格，即时确认。",
  "home": "首页",
  "back": "返回",
  "h1": "在此预订享最优价格",
  "currencyNote": "需要将US$转换为您的货币？使用",
  "currencyConverter": "货币转换器",
  "howtoHeading": "如何预订",
  "howtoStep1Title": "Choose your unit",
  "howtoStep4": "Safari Tent • Comfort Tent • Garden Cottage • Thatched Chalet",
  "howtoStep2Title": "Decide on the Dates",
  "howtoStep2": "The longer you stay, the better the rate",
  "howtoStep3Title": "Fill in the number of adults/children",
  "howtoStep3": "Max. 2 adults + 1 child or 1 adult and 2 children per unit. Except for the Garden Cottage; max. 2 adults or 1 adult + 1 child",
  "howtoStep4Title": "Click the Book button",
  "childHeading": "带儿童旅行",
  "childBabyTitle": "婴儿 0-3岁",
  "childBabyPrice": "免费",
  "childBabyBooking": "预订时不要添加",
  "childBabyNote": "如需要，请在预订表格上添加婴儿床或在备注栏中提及",
  "childChildrenTitle": "儿童 4-11岁",
  "childChildrenPrice": "半价",
  "childChildrenBooking": "选择入住人数时添加",
  "childChildrenBed": "总人数为3时将提供额外的Safari床",
  "childYoungsterTitle": "12岁及以上青少年",
  "childYoungsterPrice": "按成人计算",
  "modalTitle": "为何直接预订？",
  "modalRate": "最优价格保证",
  "modalRateDesc": "直接预订享受最低价格",
  "modalSecure": "安全支付",
  "modalSecureDesc": "您的数据受行业标准加密保护",
  "modalNofees": "无隐藏费用",
  "modalNofeesDesc": "所见即所付 - 价格透明",
  "modalInstant": "即时确认",
  "modalInstantDesc": "立即收到您的预订确认",
  "modalSupport": "DEVOCEAN团队支持",
  "modalSupportDesc": "我们专业团队提供个性化协助",
  "units": {
    "safari": "Safari 帐篷",
    "comfort": "舒适帐篷",
    "cottage": "花园小屋",
    "chalet": "茅草木屋"
  }
};