export default {
  "title": "Bhukha ukuhlala kwakho – DEVOCEAN Lodge",
  "desc": "Ikhasi lokuphatha okuqondile le-DEVOCEAN Lodge, Ponta do Ouro, Mozambique. Amanani amahle, isiqinisekiso esisheshayo.",
  "home": "Ikhaya",
  "back": "Emuva",
  "h1": "Bhukha lapha ngeNani Elihle",
  "currencyNote": "Udinga ukuguqula US$ ibe yimali yakho? Sebenzisa ",
  "currencyConverter": "isiguquli semali",
  "howtoHeading": "Indlela yokubhukha",
  "howtoStep1Title": "Khetha indlu yakho",
  "howtoStep1": "Itende le-Safari • Itende le-Comfort • I-Cottage yensimini • I-Chalet ye-Thatch",
  "howtoStep2Title": "Nquma ngosuku",
  "howtoStep2": "Lapho uhlala isikhathi eside, intengo iba ngcono",
  "howtoStep3Title": "Faka inani labantu abadala/izingane",
  "howtoStep3": "Maks. 2 abantu abadala + 1 ingane noma 1 umuntu omdala nabantwana aba-2 ngeyunithi. Ngaphandle kwe-Garden Cottage; maks. 2 abantu abadala noma 1 umuntu omdala + 1 ingane",
  "howtoStep4Title": "Chofoza ukubhukha",
  "howtoStep4": "Bese ugcwalisa ifomu",
  "childHeading": "Uvakasha nezingane",
  "childBabyTitle": "Izinsana 0-3 yeminyaka",
  "childBabyPrice": "Mahhala",
  "childBabyBooking": "Ungangezi lapho ubhukha",
  "childBabyNote": "Engeza i-babycot kufomu yokubhukha uma kudingeka noma ukhankase endaweni yenota",
  "childChildrenTitle": "Izingane 4-11 yeminyaka",
  "childChildrenPrice": "Intengo Ephakathi",
  "childChildrenBooking": "Engeza lapho ukhetha inombolo yabahlali",
  "childChildrenBed": "Umbhede we-Safari ongeziwe uzonikezwa lapho isibalo siba ngu-3",
  "childYoungsterTitle": "Intsha kusukela ku-12 yeminyaka",
  "childYoungsterPrice": "Zibalwa njengabantu abadala",
  "modalTitle": "Kungani ubhukha ngqo?",
  "modalRate": "Inani Elihle Kuqinisekisiwe",
  "modalRateDesc": "Amanani aphansi kakhulu lapho ubhukha ngqo",
  "modalSecure": "Ukukhokha okuphephile",
  "modalSecureDesc": "Idatha yakho ivikelwe nge-encryption evamile",
  "modalNofees": "Ayikho izindleko ezifihlakele",
  "modalNofeesDesc": "Lokho okubonayo yilokho okukhokha - amanani acace",
  "modalInstant": "Isiqinisekiso esisheshayo",
  "modalInstantDesc": "Thola isiqinisekiso sakho sokubhukha ngokushesha",
  "modalSupport": "Ukwesekwa kwethimba le-DEVOCEAN",
  "modalSupportDesc": "Usizo lomuntu siqu oluvela ethimbeni lethu elizinikele",
  "units": {
    "safari": "Itende le-Safari",
    "comfort": "Itende le-Comfort",
    "cottage": "I-Cottage yensimini",
    "chalet": "I-Chalet ye-Thatch"
  }
};